# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QFileDialog, QMainWindow, QApplication

import time

from results_window import Ui_MainWindow

import sys


class MyResultWindow(QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super(MyResultWindow, self).__init__(parent)
        self.setupUi(self)



class Ui_Dialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(678, 400)
        Dialog.setMinimumSize(QtCore.QSize(678, 400))
        self.lineEdit_titel = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_titel.setGeometry(QtCore.QRect(290, 20, 113, 20))
        self.lineEdit_titel.setObjectName("lineEdit_titel")
        self.graphicsView_cover = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_cover.setGeometry(QtCore.QRect(450, 120, 91, 101))
        self.graphicsView_cover.setObjectName("graphicsView_cover")
        self.lineEdit_genre = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_genre.setGeometry(QtCore.QRect(290, 70, 113, 20))
        self.lineEdit_genre.setObjectName("lineEdit_genre")
        self.label_genre = QtWidgets.QLabel(Dialog)
        self.label_genre.setGeometry(QtCore.QRect(270, 50, 47, 13))
        self.label_genre.setObjectName("label_genre")
        self.label_titel = QtWidgets.QLabel(Dialog)
        self.label_titel.setGeometry(QtCore.QRect(270, 0, 47, 13))
        self.label_titel.setObjectName("label_titel")
        self.lineEdit_year = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_year.setGeometry(QtCore.QRect(550, 20, 61, 20))
        self.lineEdit_year.setText("")
        self.lineEdit_year.setObjectName("lineEdit_year")
        self.label_year = QtWidgets.QLabel(Dialog)
        self.label_year.setGeometry(QtCore.QRect(530, 0, 47, 13))
        self.label_year.setObjectName("label_year")
        self.lineEdit_rate = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_rate.setGeometry(QtCore.QRect(290, 120, 113, 20))
        self.lineEdit_rate.setObjectName("lineEdit_rate")
        self.label_rate = QtWidgets.QLabel(Dialog)
        self.label_rate.setGeometry(QtCore.QRect(270, 100, 71, 16))
        self.label_rate.setObjectName("label_rate")
        self.label_regisseure = QtWidgets.QLabel(Dialog)
        self.label_regisseure.setGeometry(QtCore.QRect(270, 150, 71, 16))
        self.label_regisseure.setObjectName("label_regisseure")
        self.lineEdit_regisseur = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_regisseur.setGeometry(QtCore.QRect(290, 170, 113, 20))
        self.lineEdit_regisseur.setObjectName("lineEdit_regisseur")
        self.label_produzenten = QtWidgets.QLabel(Dialog)
        self.label_produzenten.setGeometry(QtCore.QRect(270, 200, 71, 16))
        self.label_produzenten.setObjectName("label_produzenten")
        self.lineEdit_produzenten = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_produzenten.setGeometry(QtCore.QRect(290, 220, 113, 20))
        self.lineEdit_produzenten.setObjectName("lineEdit_produzenten")
        self.label_imdbnr = QtWidgets.QLabel(Dialog)
        self.label_imdbnr.setGeometry(QtCore.QRect(530, 40, 71, 16))
        self.label_imdbnr.setObjectName("label_imdbnr")
        self.lineEdit_imdbnr = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_imdbnr.setGeometry(QtCore.QRect(550, 60, 61, 20))
        self.lineEdit_imdbnr.setReadOnly(True)
        self.lineEdit_imdbnr.setObjectName("lineEdit_imdbnr")
        self.tableView_movies = QtWidgets.QTableView(Dialog)
        self.tableView_movies.setGeometry(QtCore.QRect(10, 10, 241, 331))
        self.tableView_movies.setObjectName("tableView_movies")
        self.pushButton_start = QtWidgets.QPushButton(Dialog)
        self.pushButton_start.setGeometry(QtCore.QRect(310, 310, 75, 23))
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_exit = QtWidgets.QPushButton(Dialog)
        self.pushButton_exit.setGeometry(QtCore.QRect(530, 310, 75, 23))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_open = QtWidgets.QPushButton(Dialog)
        self.pushButton_open.setGeometry(QtCore.QRect(100, 350, 75, 23))
        self.pushButton_open.setObjectName("pushButton")
        self.pushButton_search = QtWidgets.QPushButton(Dialog)
        self.pushButton_search.setGeometry(QtCore.QRect(420, 20, 75, 23))
        self.pushButton_search.setObjectName("pushButton_search")
        self.label_cover = QtWidgets.QLabel(Dialog)
        self.label_cover.setGeometry(QtCore.QRect(480, 100, 71, 16))
        self.label_cover.setObjectName("label_cover")


      #  self.pushButton_open.clicked.connect(self.chooseFolder) # type: ignore
        self.pushButton_open.clicked.connect(self.chooseFolder) # type: ignore
       # self.pushButton_search.clicked.connect(self.searchWithTitel)
        self.pushButton_search.clicked.connect(self.openResultWindow)
        self.pushButton_exit.clicked.connect(exit)

        self.pushButton_start.clicked.connect() # todo

        self.retranslateUi(Dialog)



        '''
        self.pushButton_start.clicked.connect(self.pushButton_start.click) # type: ignore
        self.pushButton_exit.clicked.connect(self.pushButton_exit.click) # type: ignore
        self.pushButton_search.clicked.connect(Dialog.exec) # type: ignore
        self.pushButton_open.clicked.connect(self.pushButton.click) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
'''
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Auto Movie Tagger "))
        self.lineEdit_titel.setToolTip(_translate("Dialog", "Titelname"))
        self.graphicsView_cover.setToolTip(_translate("Dialog", "Cover"))
        self.pushButton_search.setText(_translate("Dialog", "Search"))
        self.lineEdit_genre.setToolTip(_translate("Dialog", "Genre"))
        self.label_genre.setText(_translate("Dialog", "Genre"))
        self.label_titel.setText(_translate("Dialog", "Titel"))
        self.lineEdit_year.setToolTip(_translate("Dialog", "Year"))
        self.label_year.setText(_translate("Dialog", "Year"))
        self.lineEdit_rate.setToolTip(_translate("Dialog", "IMDB Rate"))
        self.label_rate.setText(_translate("Dialog", "IMDB Rate"))
        self.label_regisseure.setText(_translate("Dialog", "Regisseur"))
        self.lineEdit_regisseur.setToolTip(_translate("Dialog", "Regisseur"))
        self.label_produzenten.setText(_translate("Dialog", "Producer"))
        self.lineEdit_produzenten.setToolTip(_translate("Dialog", "Producer"))
        self.label_imdbnr.setText(_translate("Dialog", "IMDB Number"))
        self.lineEdit_imdbnr.setToolTip(_translate("Dialog", "Not Enabling"))
        self.pushButton_start.setText(_translate("Dialog", "Start"))
        self.pushButton_exit.setText(_translate("Dialog", "Exit"))
        self.pushButton_open.setText(_translate("Dialog", "Open"))
        self.label_cover.setText(_translate("Dialog", "Cover"))



        ''' Events '''




    ## For choosing the Movie Folder
    def chooseFolder(self):
        fd = QFileDialog()
        dirfolder = fd.getExistingDirectory(self, "Select Folder", ".") #OpenFileName(self, "Datei oeffnen", ".", "Nur bilder (*.jpg *.png)")
        print ( dirfolder )

    ## Open the second Window
    def openResultWindow(self):
        if len(self.lineEdit_titel.text()) != 0:
            self.window = QtWidgets.QMainWindow()
            self.ui = MyResultWindow()
            self.ui.setupUi(self.window)
            self.ui.lineEdit_titel.setText(self.lineEdit_titel.text())
            self.ui.searchMovies()
            self.window.show()


'''
        print(self.lineEdit_titel.text())
        if len(self.lineEdit_titel.text())!= 0:
            imdb = Cinemagoer()
            print(imdb.search_movie("Matrix"))

            appResult = QApplication(sys.argv)
            resultWindow = MyResultWindow()
            resultWindow.show()
            sys.exit(appResult.exec())
'''